# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9277c20a1a7a42f39e425b3ce8888eed58bf1f28b059f08d80b43532b27527b425c3361bb62c8417a1352fe37d5e323a4ddd5f87bbfbcd35e8b65ac6a9f2215

test:
  secret_key_base: e12119dd7d67a55d266e707e366cca4ca4a745d6a3f27778b7b80f1c91dcb1ef0669b5b7a798f66619ff9677e282fb0df3be7ec6d2122d91ba54c830f953b7fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
