# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2012d118c8c84b544eaaccb1247348e5c9a4a1e6a71a5c02295953f392ea8a3b397d941e3a381c68e8f6402fdefbd22345e2ff649d22949d29e1d807f92b378e

test:
  secret_key_base: 48ff56ba1d9861ea489b25f70b923115932f3d239e93d0cdad1bade28b28654592938b44db7976f8090ef72d1fd6922d614cf9e215f9c12ffda56ebed9336751

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
